### ISSUE TITLE
helm install fails on k3s (both arm32 and amd64)

### ISSUE THREAD

**Issue by rolinux** [alexellis/k8s-tls-registry#2]
Tried on k3s on a Raspberry Pi3 and a k3s on a AMD64 and in both cases for:

`helm init --skip-refresh --upgrade --service-account tiller`

I got:

```root@nuc:~# helm init --skip-refresh --upgrade --service-account tiller
Creating /home/radu/.helm 
Creating /home/radu/.helm/repository 
Creating /home/radu/.helm/repository/cache 
Creating /home/radu/.helm/repository/local 
Creating /home/radu/.helm/plugins 
Creating /home/radu/.helm/starters 
Creating /home/radu/.helm/cache/archive 
Creating /home/radu/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/radu/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
```

This fails as well:

```root@nuc:~# helm init --service-account tiller
$HELM_HOME has been configured at /home/radu/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
```

Is this documentation compatible with k3s or we are missing some step after helm and tiller install with `curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash` and creation of the account as requested.

**Comment by alexellis** [comment]
Hi this is because of the way k3s uses root permissions for its config file.

My tutorial tells you to use k3sup to install k3s, if you use that then it should correct the permissions.

I'm going to close the issue because this tutorial is not advertised to work on arm in any case.

Alex
